### ISSUE TITLE
Feature request: "Resend Email" button on donation details page

### ISSUE THREAD

**Issue by rafecolton** [Charitable/Charitable#165]
It would be great if there were a way to resend the donation receipt email from the donation details page.

**Comment by ericnicolaas** [comment]
I have been playing around with this today. I think there are a number of approaches we could take.

**Actions meta box:**

![Actions metabox](https://cloud.githubusercontent.com/assets/507025/25785563/792113d8-3349-11e7-8361-19924ad0a1bb.png)

This might be the most flexible option going forward, since it opens up the possibility for other donation actions too. 

**Include in donation log:**

![screenshot 2017-06-20 16 11 29](https://user-images.githubusercontent.com/676582/27319958-2ad6adbc-55d3-11e7-8079-0f90c76c4992.png)

This is a subtler approach and very minimalistic. One nice aspect of this is that we're actually conveying more information about when the emails were originally sent. However, this won't show anything for emails that haven't been sent yet. i.e. If you have a pending donation and you're wondering why the email hasn't been sent yet, this won't clarify anything for you.

To make the resend/retry links more obvious, they could be turned into buttons instead.

**Separate log:**

![screenshot 2017-06-20 16 45 09](https://user-images.githubusercontent.com/676582/27321148-470668ec-55d8-11e7-81e7-71635cdb79d1.png)

A third approach that splits the email log into its own meta box. It's a bit ugly, but it's more flexible than the donation log approach above. That said, I feel like this is just bound to increase the confusion for end users, and feels kind of like an overblown approach.

@rafecolton @helgatheviking @wesfranklin Would love your input (and anyone else)!

**Comment by helgatheviking** [comment]
I am probably biased, but I still like the actions metabox. Its easily extensible with any future emails. The records can still be kept in the donation log. The second option doesn't really allow for plugins to add their own custom emails and the last option is too convoluted imo.

**Comment by ericnicolaas** [comment]
@helgatheviking I think you're right about the Actions meta box feeling like the most easily extensible. Also second the idea of keeping the records in the donation log.

**Comment by ericnicolaas** [comment]
I have cleaned up the styling of the Actions meta box to make it more consistent with the footer of the donations table on the left: 

![screenshot 2017-07-03 14 34 40](https://user-images.githubusercontent.com/676582/27778794-e415c186-5ffc-11e7-8d60-19b3b0ad4050.png)

**Comment by ericnicolaas** [comment]
To do: 

- [ ] Do not display action options if not relevant to donation. Email resend options shouldn't be available for pending donations.
- [ ] Maybe: Change the text of the button to something appropriate given the action.
- [ ] Maybe: Only show the button when an action has been selected or changes have been made to the donation.

**Comment by ericnicolaas** [comment]
My working branch for this is `feature/actions-metabox`: https://github.com/Charitable/Charitable/tree/feature/actions-metabox

**Comment by ericnicolaas** [comment]
I have pushed a bunch of under the hood changes to the way the donation functionality is set up in the admin (see 9bd1352). As part of that, the plan is to have a simple method for returning all the available actions for a given donation: 

`Charitable_Donation_Metaboxes::get_donation_actions()`

This will include a filter (`charitable_donation_actions`) which allows extra actions to be registered.

**Comment by ericnicolaas** [comment]
@wesfranklin Can I get you to take a look at the design I posted? Any ideas for improvement?

**Comment by wesfranklin** [comment]
@ericnicolaas Looks pretty solid.

**Comment by ericnicolaas** [comment]
I have rolled out a major series of changes. The big thing here is the addition of an abstract `Charitable_Admin_Actions` class with a concrete `Charitable_Donation_Admin_Actions` class, where admin actions are registered. This design allows us to introduce similar classes with actions that can be taken for campaigns, donors, etc.

Registering an action is fairly straightforward:

```
charitable_get_donation_actions()->register( $action_hook, $args, $group = 'default' );

// Example:
charitable_get_donation_actions()->register( $action_hook, array(
	'label'                  => 'Action label',
	'callback'            => 'function_to_execute',
	'button_text'       => 'Button text',
	'active_callback' => 'function_to_check_whether_action_is_available',
), 'Group' );
```

I'm also planning on adding a way to set the success message & failure message for a particular action.

This is about 80% there. The button text does not change dynamically, and the donation emails are currently always available as actions, even though they probably shouldn't be for pending donations.

**Comment by ericnicolaas** [comment]
This is nearly done. Only remaining item is to provide success & failure messages for a given action.

**Comment by ericnicolaas** [comment]
Done! Very pleased to get this one ready. It's now ready to be tested in the latest master & alpha.

**Comment by rafecolton** [comment]
Looks like I'm a little late to the party. Happy to see this has been implemented! 

I do think it would be useful to have a separate Email Log metabox. Conceptually it seems useful—most of the items in the Donation Log are passive / informative, whereas the email log items are all actionable. If there were to be an Email Log metabox, I would still expect to see the email items in the Donation Log but only to put them in chronological order with other donation actions.

I could also see a separate Email Log being useful for integrating Charitable with a transaction email service, such as MailChimp's Mandrill, where there might be a need to display more data, per log item, that are specific to emails.

That all being said, this looks like a great and very useful initial implementation. Thanks @ericnicolaas for building this!

**Comment by ericnicolaas** [comment]
@rafecolton That's an interesting idea! Could you post that concept as a separate issue? Not something I want to tackle in 1.5, but can definitely see the value in being able to toggle to something like Mandrill's record for a particular email send. We'd need to do a bunch more capturing of data about emails before we get to that though.
