### ISSUE TITLE
Allow new donations to be created in the dashboard

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#241]
Sort of related to #118.

One challenge to adding this feature is regarding the email addresses of donors. If people are collecting donations offline, there is a good chance that they do not have an email address for the donor. However, in order to add a donation in Charitable, an email address is required.

So the question is, do we: 
- Require email addresses for all manually created donations 
- Make the email address an optional field

Making the email address optional could have some far-reaching effects. Receipts obviously can't be sent to the donor. Any situation where an email address is expected would have to be changed to allow for the possibility of no email existing.

You also end up with the possibility of duplicate donors, since there is no email address there making sure that donations from the same person attributed to the same donor. Adding an offline donation for John Smith? It might be the John Smith that's donated before, but without an email address, you don't know for sure.

**To Do**

- [ ] Set date of donation.
- [ ] Link to Add New donation form.
- [ ] Allow admin to leave a note explaining how the donation was received.
- [ ] Allow admin to select donor from existing list of donors.
- [ ] Set status of donation.
- [ ] Add option to send donation receipt via email.

**Comment by rafecolton** [comment]
Another issue is that if the donor email address is provided, it could be confusing for them to get a message about a donation if they've already given cash or a check. 

Still, it might be good to keep the email address mandatory for consistency—the admin can always enter his/her own email address (or accounting team's email address) if the donor does not have one available. Additionally, it could be helpful to optionally not send any emails to the donor when entering the donation by this method

**Comment by ericnicolaas** [comment]
Wow, fast comments @rafecolton !

> Still, it might be good to keep the email address mandatory for consistency—the admin can always enter his/her own email address (or accounting team's email address) if the donor does not have one available. 

Yes, and this is probably what would have to happen. The problem is that the donor count on campaigns is based on the number of unique donors to a campaign. If the admin adds 100 donations under his/her own email address, those will all be considered to have come from a single donor for the purposes of the donor count.

> Additionally, it could be helpful to optionally not send any emails to the donor when entering the donation by this method

Great point! I guess the form should just include a simple checkbox to allow people to choose whether the donation receipt should be sent.

**Comment by rafecolton** [comment]
Admin could always do something like admin+donor-name@example.com to keep the emails unique

**Comment by ericnicolaas** [comment]
True, and if we went with keeping email addresses required, that's probably exactly what I'd recommend to users.

**Comment by lukepg** [comment]
Give ( https://github.com/WordImpress/Give ) has some addons that integrate issuing online Tax receipts. This is one of the biggest headaches in operating a small non-profit. The government guidelines can be very specific in terms of what is required on the receipt from donor name & address to the format of the receipt ID. If there was some interest in going further in this direction I would be happy to provide comments.

Regarding simply the manual donations, I think it would be best to have the email address be optional. But as rafecolton mentioned, this brings up the question of whether emails will ever be sent to the donor. Our donors love getting tax receipts by email though as it is simple for them to forward to their accountants. I'm not sure what other messages might be sent to them but grouping them by email could add the possibility of a user creating an online account in the future and perhaps then claiming their prior donations for their records. Or, even to download their tax receipts ;)

And from my previous post, I would really like the feature to bulk update the counter by donor quantity and amount. The issue is really with the donor count because now it does a sum on the number of donor records. I would need some way to add a certain number of donors and donations that were received offline without inputting every single one. We might have 50 donors who gave less than $5 and it can be very time consuming to input all of that data.

**Comment by ericnicolaas** [comment]
Thanks for the feedback @lukepg! 

Would definitely love feedback/suggestions for any way to improve the receipts that are sent out by Charitable, particularly if those need something extra for tax requirements. Please add those as a separate issue — helps me stay sane :)

>I'm not sure what other messages might be sent to them but grouping them by email could add the possibility of a user creating an online account in the future and perhaps then claiming their prior donations for their records. Or, even to download their tax receipts ;)

The donation receipt is the main email that donors would receive. But yes, being able to register on the site and then access receipts for previous donations is one of the major benefits of having an email for their donation.

Regarding the bulk update, I have re-opened your other issue, but one question: If Charitable included a way to import donations via a CSV file, would that be another way of solving your problem?

**Comment by lukepg** [comment]
Thanks for your response Eric. Ok, I will submit a new post specifically about tax receipts. 

Well, a CSV import may be a very good and useful tool. It would probably speed up data entry on some level. In our very specific situation right now, we would then still have to type the records into a spreadsheet. I would probably just end up creating dummy records so I could copy and paste 300 fake donors. But I would hate the fact that I was filling up and table with dummy records. Also, creating a CSV does require a basic level of sophistication that many users probably do not have. 

For a quick solution, another way could be to look at it as seed values. It's also likely that some people may be hesitant be the first contributer to a campaign. But if there are already 5 or 10 donors and some money raised, people might be quicker to contribute. So if you had Seed Donor Count and Seed Donor Amount in each Campaign settings, this would solve the problem in a very quick and easy way. Then when the total functions are called they Seed amounts just get added. We could just go back and update the Seed values when necessary.

**Comment by SooBahkDo** [comment]
Manual entry of donations via the admin would be very helpful for us. 

Staff members who take donations by phone and process donations received by mail often need to add those donations to a campaign, but Charitable does not currently provide a convenient means for staff members to add these donations on behalf of donors.

**Comment by ericnicolaas** [comment]
This is an early iteration of the admin donation form:

![screenshot 2017-09-22 15 03 38](https://user-images.githubusercontent.com/676582/30730582-3fe2f63e-9fa7-11e7-900d-f69a009691c7.png)

This same form can be used for editing existing donations (see #118) and adding new donations.

**Comment by ericnicolaas** [comment]
A few things to note: 

**This does not support adding donations to multiple campaigns at once.** Technically Charitable does support that from a database-structure point of view, but it's not something that is used unless you are using the Easy Digital Downloads integration. Considering this is basically a hidden "feature" of Charitable, I think it's reasonable to not support it in the admin form.

There are additional meta fields that are not appearing here, which we can add through updates to extensions. i.e. We could release an update to Anonymous Donations that shifts to the Donation Fields API and automatically adds support for making anonymous donations via the admin form.

**Comment by ericnicolaas** [comment]
Fleshed this out further, with the ability to select an existing donor and additional meta fields added for donation:

### New donation

![screenshot 2017-09-25 11 49 29](https://user-images.githubusercontent.com/676582/30789896-bbbfa134-a1e7-11e7-89ca-aa8d169a2229.png)

### Selecting a donor

![screenshot 2017-09-25 11 50 46](https://user-images.githubusercontent.com/676582/30789910-cbdfbb4e-a1e7-11e7-814e-77c2b5567e26.png)

### Adding a new donor

![screenshot 2017-09-25 11 51 15](https://user-images.githubusercontent.com/676582/30789923-dcb5f9b0-a1e7-11e7-8d81-f22a9a9bf9c3.png)

### Setting the donation date

![screenshot 2017-09-25 11 51 37](https://user-images.githubusercontent.com/676582/30789931-e98963de-a1e7-11e7-8238-7e2ed0e38b1c.png)

### Editing an existing donation

![screenshot 2017-09-25 11 52 03](https://user-images.githubusercontent.com/676582/30789946-f9771d18-a1e7-11e7-8daa-206ede65c69b.png)

**Comment by ericnicolaas** [comment]
I was unconvinced with having the form in a single column. In order to not have super wide fields, I was limiting the width of the column to 600px, but that left acres of space over to the right on desktops.

As an alternative, we can split the "Additional Details" section into a separate meta box and use the full width of the form:

![screenshot 2017-09-25 16 52 30](https://user-images.githubusercontent.com/676582/30796604-f7417faa-a211-11e7-8f6b-e1760c51d6b0.png)

![screenshot 2017-09-25 16 52 57](https://user-images.githubusercontent.com/676582/30796617-03a153ec-a212-11e7-92ff-fc064280665d.png)

**Comment by lukepg** [comment]
I think that the way you have it looks really awesome Eric. Great job,
thanks for your efforts. I will reflect and see if I have any further
suggestions to add.

**Comment by ericnicolaas** [comment]
Thanks @lukepg — great to get your feedback!

**Comment by memerson75** [comment]
@ericnicolaas, the form looks great! Perhaps you could eliminate the donor details (like name and address) and simply require that a donor be entered separately before adding the donation? It looks like that's how it was on your original single-column version.

The non-profit I'm working with often gets checks without email addresses, and sometimes without physical addresses. For the former, if you choose to make it required, we can have them use the workaround suggested by @rafecolton.

**Comment by lukepg** [comment]
Hi Eric,

  Thanks for your hard work on this. Just to reiterate some of the points made above regarding the donor count and donor entry. I see a couple items which may be relevant. US IRS donation receipt requirements are fairly lax so I wouldn't be worried about conforming. But Canadian charitable receipts are strict. You can see their guidelines here:
https://www.canada.ca/en/revenue-agency/services/charities-giving/charities/sample-official-donation-receipts.html
https://www.canada.ca/en/revenue-agency/services/charities-giving/charities/operating-a-registered-charity/issuing-receipts.html

 It seems that most donation receipt issuing software struggle most with the unique donation id requirement. This is unique to each receipt issued but a receipt can be for a single or multiple (lumped) donations. It also should be maintained for record keeping meaning it can't just add some random ID, issue a receipt and forget about it. We must also be able to print/send duplicate receipts which say "Duplicate Copy" on it but is otherwise identical. And Issue Date could be important too. Generally we will put the Issue Date as Dec 31st but not necessarily. The legal deadline to issue receipts in Canada is January 31st, I think. 

 In terms of donor entry and donor count, we were concerned with our donor counter. And as you pointed out, it counts donors rather than donations. Most people like us would like to see the number as high as possible as it looks good so we will easily count two donations from a single donor as two, for other people they might prefer the opposite. 

 But in terms of us managing the online counter, let's say we have a big fundraiser and raise 1,000 offline donations. If Charitable had very good receipt issuing layout and accounting, it might be worth to manually enter them all including email, address, etc. But otherwise it might be good to allow for a quick entry with just name, amount, date received & status.

  I almost forgot, please add a Confirmation dialogue box when pressing "Trash" donation. If this is the only record of the donation then accidentally deleting it could be catastrophic. 

  Thank you and sorry for the long post.

Luke

**Comment by ericnicolaas** [comment]
Thanks for the feedback Luke! Great information re. Canadian receipts. Quick question: Do the duplicates have to say "Duplicate Copy" or can it be something to that effect? i.e. How strict is that?

**Comment by lukepg** [comment]
Hi Eric,

   It does not have to have that exact wording. Quoting their website:

“a statement that it replaces the original receipt”


Thanks,
Luke
