### ISSUE TITLE
charitable_get_donation() returns an object when creating a donation from an incorrect post type

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#245]
If you pass `charitable_get_donation()` a post or page ID, then it still returns a donation object. Just opening this for discussion.... should it return false if the ID/post passed to the donation factory is not actually a donation?

**Comment by ericnicolaas** [comment]
Yeah, seems like it should return `false`. If a `Charitable_Donation` object is returned, it should actually be a donation :)

**Comment by ericnicolaas** [comment]
@admah: Thanks for the PR in #253 

That approach works, but it's not quite flexible enough, because `charitable_donation` is not the only post type that is valid. We have a Recurring Donations extension coming out soon which introduces a `recurring_donation` post type and it should also be able to have objects returned correctly when `charitable_get_donation` is called. 

Since we're using the factory pattern for returning donations, I'm thinking the ideal solution is to change the factory's `get_donation()` method to return `false` if the post type is not valid: 

https://github.com/Charitable/Charitable/blob/master/includes/donations/class-charitable-donation-factory.php#L49

The post type check should be set up as a filter so that other extensions like Recurring Donation can add other valid post types.
