### ISSUE TITLE
Problem with number of donations

### ISSUE THREAD

**Issue by ruayrod** [Charitable/Charitable#266]
On the front-page of campaign the number of donors does not match the actual number of donations. In the widget donations, the actual number of donations if it appears correct.
Apparently the error is to count all email accounts that are donating and not the number of individual donations made.
Example (http://www.jovenfutura.org/campaigns/por-un-ibi-justo/):
Only 50 donors appear on the page of the campaign.
In the widget you can see the actual number, 148 donors.

Sorry my bad english.

**Comment by ericnicolaas** [comment]
I just replied to your separate email about this, but just including my reply here. 

-- 

This is by design. The donor count shows the number of unique donors, not the number of donations. 

Actually, the Donation Stats widget really should display the number of unique donors as well, instead of the number of donations. See #268 

Unfortunately, this is partly a problem because there is no easy way to add manual donations. I understand why you're creating offline donations as the administrator. This is something we are planning to fix in version 1.5 by adding the ability to create donations manually in the WordPress dashboard. See #241
