### ISSUE TITLE
Improve offline donations notifications workflow

### ISSUE THREAD

**Issue by altatof** [Charitable/Charitable#33]
when offline donation is done (without waiting for the payment) :
- thanks the donator with an email
- notify the campaign manager with an email

when donation payment is set from pending to paid : 
- thanks the donator again :)

**Comment by ericnicolaas** [comment]
I'm not sure if this is something that suits the core plugin, since it could get confusing if you are using PayPal or other payment gateways (it would be very easy to double up on emails to donors). I'm going to tag it as something to consider for a future add-on. 

Cheers, 
Eric

**Comment by altatof** [comment]
in my point of view, we can make a test on the donation status and if offline we use the proposed workflow, don't you agree ?
On the other hand, i guess i can do it by using charitable hooks, but i really think that the donator must be thanked just after the donation, and even more that the wp admin should be notified of the offline donation.

**Comment by ElStupid** [comment]
Yes I very much agree on this situation. I'm also finding myself with pending donations. There's no way of knowing about an offline donation other than to check every now and then.

Also I would like to see them included in the progress bar and the total amount of donations. Maybe could be done through a setting. But that's another discussion I guess.

**Comment by ericnicolaas** [comment]
Just to summarize issues that you have both brought up, as well as other users:

* When someone first makes a donation, their donation is Pending. As such, they do not receive the Donation Receipt, since that is only sent when a donation is Paid.
* The admin is also not notified about the Donation, because the admin notification is only sent for Paid donations.

There are a few ways that this could be resolved. One thing that many people have done is to simply have one or both of those emails sent immediately after an Offline Donation is made, even though it's pending. That can be done with these two code snippets:

* https://github.com/Charitable/library/blob/master/emails/send-donation-notification-for-pending-offline-donations.php
* https://github.com/Charitable/library/blob/master/emails/send-donation-receipt-for-pending-offline-donations.php

One comment though is that the email that a donor receives after making an Offline Donation might need to be different than the donor receives after completing payment for a donation (either an Offline Donation or one made through PayPal/Stripe/etc). For example, it might be useful for organizations to send the payment instructions via email to the donor.

So an alternative might be to introduce a separate email for donors that is only sent for Offline Donations while they are Pending.

**Comment by rafecolton** [comment]
Since we use offline donations as pledges, I have code handy for sending emails to the pledger and admin when an offline donation is submitted. I can submit a PR with that code if you would like to use it as a solution here. Bonus is that new emails are always opt in so it won't negatively affect anyone using offline donations for another purpose.

**Comment by rafecolton** [comment]
And I'm reasonably certain that when the offline donation gets marked as paid, both admin and donor get an email. I'll double check if you would like me to address this one.

**Comment by ericnicolaas** [comment]
@rafecolton That sounds pretty much like what we need! Just to confirm, you're registering a new email? i.e. A standard Charitable email? 

Would love to review a PR :)

**Comment by rafecolton** [comment]
Exactly. Will do.

**Comment by helgatheviking** [comment]
I think that sending emails on post status transition should help. #217 (though that's still got a few kinks to work out). And the ability to manually resend emails will also help. #216

**Comment by ericnicolaas** [comment]
#338 adds the ability to include offline donation instructions and also registers a new receipt email for donors that only gets sent for pending donations that are offline. 

One thing we're still missing then is a notification for the admin. We could either register a new email for that, or make the existing admin notification smarter about when it gets sent.

**Comment by helgatheviking** [comment]
The admin 'new donation' notification isn't sent? It could display the status to differentiate between completed and offline.

**Comment by ericnicolaas** [comment]
No, the admin notification only goes out when the donation is marked as paid. So the problem at the moment is that admin aren't aware of new offline donations until they log in.

Potentially we could just tweak the admin notification so that it sends automatically for pending offline donations, and for paid donations from other gateways.
