### ISSUE TITLE
Question: getting permalink of campaign from donation receipt page

### ISSUE THREAD

**Issue by qriouslad** [Charitable/Charitable#336]
Hi guys,

I'm adding custom code to the donation receipt page by modifying https://github.com/Charitable/Charitable/blob/master/templates/donation-receipt/summary.php in my child theme.

Could you point me in the right direction on how to obtain the campaign's title and permalink from the donation receipt page (e.g. page ending in /receipt-page-slug?donation_id=1050)?... I'm not seeing that information on print_r($donation).

Thanks!
Bowo

**Comment by ericnicolaas** [comment]
There isn't a super easy way to do that, mostly because I have shied away from assuming that each donation is one for a single campaign (even though that is mostly true at the moment).

That said, you can use this code snippet as an example of how to grab the campaign permalink:

https://github.com/Charitable/library/blob/master/donation-receipt/add-campaign-link.php

**Comment by qriouslad** [comment]
Thanks @ericnicolaas, these lines are all I need:

$campaigns = $donation->get_campaign_donations();
$campaign_donation = current( $campaigns );
$campaign_permalink = get_permalink( $campaign_donation->campaign_id );
