### ISSUE TITLE
Nonce Error: Improve error message language

### ISSUE THREAD

**Issue by tchristian32** [Charitable/Charitable#549]
I am unable to see what is happening when a user gets the following error trying to pay:

```
Unable to submit form. Please try again.
There was an error with processing your form submission. Please reload the page and try again.
```

I have tried turning on WP_DEBUG and WP_DEBUG_LOG but don't see any messages on what is happening.

**Comment by ericnicolaas** [comment]
This specific error happens when a nonce check fails, or the honeypot field was filled out. I have updated the issue title to make that a bit clearer. 

The error could be tweaked to specifically say it's related to a security check:

> Unfortunately, a security check failed when we tried to processed your form submission. Please reload the page and try again. 

However, I'm concerned about this phrasing as it suggests to the donor that the donation process is insecure. Consider a donor who has just filled out their card details and then gets that error — maybe they get worried about their card details being compromised and end up contacting their bank, when it has nothing to do with their card. 

Perhaps this would be better:

> Unfortunately, we were unable to verify your form submission. Please reload the page and try again. 

@wesfranklin What are your thoughts on this?

**Comment by wesfranklin** [comment]
@ericnicolaas Will reloading the page and trying again fix it?
