### ISSUE TITLE
Add client-side validation for the credit card field

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#63]
> There should be client-side validation of the credit card number, at least ensuring that it is only 
> numbers and <= 16 characters.  It would also be helpful to break it up into groups of 4 as it is typed in.

AJAX-based donations will improve this somewhat, but it makes sense to do some basic credit card validation before firing anything off to the gateways.

**Comment by rafecolton** [comment]
@ericnicolaas FYI work for this has been started [here](https://github.com/cyhtan/cc-helper/) by @cyhtan (we're currently using it in production)

**Comment by ericnicolaas** [comment]
Thanks for the heads up @rafecolton. @cyhtan, I've just pushed up some changes in the `master` branch that will have an impact on your work here and in #164. Basically, I have added a `CHARITABLE.Donation_Form` object to the main Charitable script. A lot of the handlers have shifted around, and there are a bunch of new helpers in there. I'd like to have the credit card validation included in there too, called in the `Donation_Form.prototype.validate` function.

**Comment by ericnicolaas** [comment]
@rafecolton and @cyhtan: Just looking over the work you have done on your end, and I think it will be a bit more than I want in Charitable right now. For the purposes of this release, I think I want to limit this validation to being a basic Luhn check, no more.

**Comment by cyhtan** [comment]
@ericnicolaas I think that makes a lot of sense. 

The only other feature I'd want to make a case for is regarding the UX of entering a credit card number. During a testing event **we had a number of users report difficulty (or give up entirely and ask for help) entering their credit card number properly**. 

The two most prevalent issues were:

- **Using the HTML `pattern` attribute gave a very unhelpful/unclear popup message** when the check failed (something like "Please match the indicated format" in Chrome, and that format was, of course, not indicated anywhere.)
- By far the most common reason that **users failed that check was because they were entering their number with spaces**, both because that's how the number appears on card faces, and because that's how people naturally process those larger numbers, in pieces.

I'm fairly confident that the combination of these issues would cause a large amount of would-be donors to abandon the process entirely. 

One very simple fix might be to remove the `pattern` attribute (ideally replacing with some client-side validation with clearer feedback), and include a simple regex server-side to remove spaces (and perhaps hyphens too) before attempting to process the payment.

A slightly more complicated UX improvement would be manually inserting spaces for users as they type their card number. I've encountered this often out in the wild, and a lot of credit card libraries offer it (see [CreditCardJS](https://creditcardjs.com/) or [Card](https://github.com/jessepollak/card), for example). 

One improvement I made over those two libraries was to keep the cursor in the correct spot and maintain proper space formatting when going back to insert or delete characters somewhere in the middle of the typed number. Try out the demo of either and you'll notice some unfortunate quirks. You can [demo my solution we're using in production here.](https://humanitarian.himalayaninstitute.org/campaigns/celebrating-10-years-of-service/donate/) 

**If you're interested, I'd be happy to pull just the relevant code (Luhn validation, and the aforementioned auto-space-insertion/formatting) and adapt for Charitable and make a PR for you to evaluate.** It would also require the server to strip spaces though, as I had to implement an unfortunate and unnecessarily elaborate workaround involving cloning and hiding the card number field in order to accommodate for Charitable needing the card number to come in without spaces, and I would not want to duplicate that here as I think handling it server-side is a much cleaner and more robust solution.

If you'd still prefer just the Luhn validation for this release, I can do that as well (or you can if it's quicker/easier). In any case, [here's the implementation I used](https://gist.github.com/ShirtlessKirk/2134376), which has better performance than some other choices out there.

**Comment by ericnicolaas** [comment]
Alright, I'm on board with that. So here are the improvements I think should be part of this in 1.4.0: 

- [ ] Remove the `pattern` attribute for the credit card number.
- [ ] Luhn check upon submission. 
- [ ] Automatically add spaces.

One note on how you have this implemented on your site: I'm not sold on the "Invalid credit card number" message immediately after filling out the field. I do see the value in providing instant feedback, but for now I'd like to keep that out of this release. The check can take place when the form is submitted. 

Also, I'm happy for all of this credit card validation stuff to be part of a separate js file. It only needs to be loaded for people who use Stripe or Authorize.Net (or any other credit card gateways we add in the future).

**Comment by cyhtan** [comment]
Great! Do you have a rough release date goal for 1.4.0? Want to make sure I prioritize accordingly and don't hold you up.

**Comment by ericnicolaas** [comment]
I would love to put a freeze on development by the middle of this week, and then spend some time testing before releasing the update early next week. Does that work for you?

**Comment by cyhtan** [comment]
Sure, I should be able to find some time tomorrow.

**Comment by cyhtan** [comment]
Hey @ericnicolaas. I've made the changes we discussed (you'll see the reference above in the issue/63 branch on my fork). A couple small, but **very important** notes regarding my changes. Essentially they require two small accompanying changes to be made before merging, otherwise they will prevent donations from going through:

- On my local instance we're using the `charitable-authorize-net` plugin (necessary for credit cards anyway?) and I was NOT able to stop the pattern attribute from being applied without modifying that plugin separately. I did remove what would seem to be an appropriate corresponding line here in Charitable, but that did not seem to have any effect when used together with the Authorize.Net plugin. **Without removing that pattern attribute from the Authorize.Net plugin, the changes I've made here will work in conjunction with that attribute to prevent the user from submitting anything, so this must be resolved before merging.**
- Of similar importance, I was not able to locate the appropriate server-side location to strip the incoming credit card number of spaces before passing along to Authorize.Net. As a result, **right now users can only submit invalid card numbers (due to the auto-formatting forcing spaces), and so anything submitted will result in an `unable to verify payment` error. This also must be resolved before merging.** 

I assume both of these changes would be quick for you to make, so hoping you can take it from here. Perhaps you can create an issue branch that I can make the PR against, and then you can make any additional changes from there? Let me know if I can do anything else to help.

**Comment by ericnicolaas** [comment]
Thanks @cyhtan -- this is looking good. Could you do a PR against `issue/63`? I'll work on the server-side changes that need to happen to accompany this.

**Comment by cyhtan** [comment]
Done, thank you @ericnicolaas!

**Comment by ericnicolaas** [comment]
@cyhtan I have had a good play around with this, and it's really good. I've made the server-side change to remove empty spaces from the credit card number. 

One further change I have made is to migrate all the credit card validation & ux stuff into its own JS file. This is to save loading the extra weight for users who do not have a credit card gateway, which is the vast majority of our active users. 

I have also set up conditional loading for the donation form scripts. Previously they were loaded everywhere; now they're just loaded when required.

I've also updated the Authorize.Net extension, though that's not released yet. @rafecolton has access to the private repo for that, so you can grab the latest `master` from there. Do be aware that there are a few other changes in there, primarily an update to the A.NET sdk if you're using PHP 5.5+. It's very much beta, so please test in staging/development before production. Any issues with that extension can be reported in its repo. If you'd like access to that repo, let me know what your Bitbucket username is. 

Thanks again for the contribution! Really happy with how this release is shaping up.

**Comment by ericnicolaas** [comment]
Thanks for all your work on this @cyhtan. Just merged it into master.
