### ISSUE TITLE
Feature request to move all Charitable content to separate Charitable tables.

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#826]
Feature request to move all Charitable content that is now in general DB tables such as wppx_posts and wppx_postsmeta to separate Charitable tables. 

Use case: 
We use both Charitable and WPML for translation. We would LIKE to use the staging option built into Softalicious to push new developments from our dev environment to the 'real' site. For this, we need to exclude the Charitable contents, because if we include it, new donors and donations that have applied through our real site are overwritten and deleted. However, we need to included the WPML content, because this is new translation content that we edited on the dev environment. However, both Charitable and WPML store their content in the general wppx_posts table, which we either have to include or exclude as a whole. So at the moment we cannot use the staging option built into Softalicious.

**Comment by Rik44444** [comment]
made the same request with MailPoet: https://feedback.mailpoet.com/integrations/p/staging-push-to-live-using-softalicious-app-installer-in-cpanel-c-panel

**Comment by ericnicolaas** [comment]
@Rik44444 I gave more detail around how the data is organized and why [here](https://github.com/Charitable/Charitable/issues/828#issuecomment-745920980), but thanks for the feedback regarding Softalicious. That's an interesting point and not one I had thought of previously. As noted in my comment, moving Charitable content into its own set of tables is a huge project and not one we're likely to do anytime soon.

Realistically, we probably wouldn't move campaigns into their own table, since they make most sense as a type of post content. It's mainly donations & recurring donations that would be served by having their own table. 

The Softalicious issue is a more general problem with pushing from staging to live. In your scenario, if you had edited any pages or posts on your live site, or uploaded any new media or anything, all of those changes would be overridden when you pushed from staging. Unfortunately, there just isn't an easy way to safely push _data_ from staging to live, because of how widely used the `wp_posts` table is. 

A few years ago there was a service called Mergebot that attempted to solve this problem, but eventually its creators abandoned it because it's simply such a difficult problem to solve. :(
