### ISSUE TITLE
DB suggestions

### ISSUE THREAD

**Issue by Rik44444** [Charitable/Charitable#828]
Hi, some DB suggestions:

- https://github.com/Charitable/Charitable/issues/826 see here for suggestion to move Charitable data from general tables to specific Charitable tables
- naming: "charitable" is very clear in the naming. "charitable_donors" also. "charitable_campaign_donations" less - would suggest to change this to "charitable_donations" 
- structure: would suggest 3 tables to correspond to the 3 big data groups: charitable_donations, charitable_donors and charitable_campaigns. It is not clear to me why the "charitable_donormeta" and "charitable_donation_fees" cannot be included in the tables about donors and donations respectively. 
- charitable_campaign_donations table: unclear to me what a "campaign_donations_ID" is, it seems to be a "donation_ID" and what is now called the "donation_ID" appears to be a central ID on your charitable servers, that issues a central ID for all charities that use your platform, is that correct? Surmised from the large and seemingly random numbers. Would rename first to "donation_ID" and second to "central_Charitable_plugin_ID" or something
- it is unclear to me where some of the data is. E.g. the charitable_donors table, it seems to have some information on the donors, but certainly not all (address, organization etc is all missing). These data also do not appear to exists in the charitable_donormeta table: that one is empty in our DB.

**Comment by ericnicolaas** [comment]
Thanks for the suggestions @Rik44444! 

Just to help explain how things are currently structured, Charitable's donations and campaigns are both set up as custom post types in WordPress. This means that their core data is stored in the `wp_posts` and `wp_postmeta` table. 

This is a fairly common practice in WordPress plugins, but we have thought about moving to specific Charitable tables for things like donations. There would likely be some performance gains from that, but it's a huge project and not one we're going to tackle anytime soon. 

The `charitable_campaign_donations` table records donations to campaigns. The reason this table exists is to allow the possibility of a single donation including donations to multiple campaigns. While this isn't something you can currently do with Charitable itself, it is possible if you use Charitable alongside Easy Digital Downloads with our EDD Connect extension — in that scenario, it's possible to make donations to multiple campaigns in a single EDD purchase. 

There aren't currently any plans to extend this ability to make donations to multiple campaigns in a single donation to Charitable core (not many people are requesting it), but that's why the table is structured that way. The `donation_id` in that table corresponds to the `ID` in the `wp_posts` table for the donation. `campaign_donations_id` is its own unique ID and can for the most part be ignored. 

I should clarify that none of your donation data is stored on our servers; everything is 100% stored in your WordPress database. 

There are some issues around how donor data is stored. When someone makes a donation, their donor details are recorded in the `donor_data` meta field for the donation in the `wp_postmeta` table. We are planning some improvements around how this works for the 1.7 release, with donor data getting updated in the `charitable_donormeta` table.

About `charitable_donation_fees`, that one is a separate table mostly because it's only there is you use the Fee Relief extension. If you don't have Fee Relief installed, that table won't be added.
